"use strict";

const alpha = document.createElement("div");
alpha.id="name";
alpha.innerHTML ="This Div is dynamically generated by mayuri";

//attach div element to the document body
document.body.appendChild(alpha);



const beta = document.createElement("div");
beta.id = "ganguly";
beta.className = 'common';
beta.innerHTML = "this is a beta div";
//Adding inline csselements
beta.style.backgroundColor="yellow";
beta.style.color="red";
beta.style.alignContent='center';
document.body.appendChild(beta);


//delete 
document.getElementById("btn1").addEventListener("click",function(){
     document.getElementById("name").remove();
})